name: goodwishes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  image_picker: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  google_sign_in: ^5.0.7
  googleapis: ^10.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_oss_licenses: ^3.0.2
  permission_handler: 

flutter:
  uses-material-design: true

  assets:
    - assets/